
language = "C"
no_includes = true
sys_includes = ["stdint.h"]
#namespace = "delta_ffi"

pragma_once = true
include_version = true
cpp_compat = true

[enum]
rename_variants = "UpperCase"

[fn]
#prefix = "DELAT_FFI"
args = "vertical"
sort_by = "None"

[parse]
parse_deps = true
include = ["delta"]

[export]
#prefix = "FFIDELTA_"

[export.rename]
"BlockHeader" = """

#ifdef _MSC_VER
#pragma pack(push,1)
BlockHeader
#pragma pack(pop)
#else 
BlockHeader
#endif
"""

# Table of things to prepend to the body of any struct, union, or enum that has the
# given name. This can be used to add things like methods which don't change ABI,
# mark fields private, etc
#[export.pre_body]
#"BlockHeader" = """
#  PREP_BODY(
#"""

# Table of things to append to the body of any struct, union, or enum that has the
# given name. This can be used to add things like methods which don't change ABI.
#[export.body]
#"BlockHeader" = """
#  )APP_BODY
#"""

[layout]
packed = "PACKED"
